### PR TITLE
NDVALPHA-NESTEDRDP-WINDOWS-VERSIONS

### PR DESCRIPTION
**Pull request by NDVALPHA**
Everything is ready.
Thank you.

### CODE REVIEW

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[89f7d27](https://github.com/NDVALPHA/SupportArticles-docs/commits/89f7d27f88bd77d92c74b353a5cd2d1a77601297)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9f3aa5b5)

<a id="9f3aa5b5"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210170834579869-752/BuildReport?accessString=f8daf30f25b1aebaff23f96da60427454671f079576d24ed2630bf481e2cb696).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[89f7d27](https://github.com/NDVALPHA/SupportArticles-docs/commits/89f7d27f88bd77d92c74b353a5cd2d1a77601297)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/windows-server/remote/run-remote-desktop-connection-session.md](https://github.com/NDVALPHA/SupportArticles-docs/blob/NDVALPHA-NESTEDRDP-WINDOWS-VERSIONS/support/windows-server/remote/run-remote-desktop-connection-session.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210180211404676-752/BuildReport?accessString=991a80f7bf8ebe9592e7d853af28dbeb3cd0264196328e30a7506b9d956561bb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[7d91778](https://github.com/NDVALPHA/SupportArticles-docs/commits/7d917788170e7e6dc62ea5c2c7c5c78b351f9f91)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/windows-server/remote/run-remote-desktop-connection-session.md](https://github.com/NDVALPHA/SupportArticles-docs/blob/NDVALPHA-NESTEDRDP-WINDOWS-VERSIONS/support/windows-server/remote/run-remote-desktop-connection-session.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210180610218012-752/BuildReport?accessString=00ef4b40e5df8fa0463eefe836f75e9676cf19bba68797b7a73a24434bfc3f65).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[5087ed5](https://github.com/NDVALPHA/SupportArticles-docs/commits/5087ed5e53e51e9e6ba706962a1ba20b0c5db965)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/windows-server/remote/run-remote-desktop-connection-session.md](https://github.com/NDVALPHA/SupportArticles-docs/blob/NDVALPHA-NESTEDRDP-WINDOWS-VERSIONS/support/windows-server/remote/run-remote-desktop-connection-session.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210180634510560-752/BuildReport?accessString=33d0031709b8deaf1aa26dfca3f3bb64eb915738704cc57b2178d1748a250b56).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by simonxjx** [comment]
@NDVALPHA, Microsoft submitters should work in the private repo. Could you follow https://review.docs.microsoft.com/help/contribute/contribute-authors-in-public-repo?branch=main to submit changes in the private repo in the future?

**Comment by NDVALPHA** [comment]
@simonxjx -> I can see that the document has been updated with the information I provided but I'm not listed as a Contributor, meaning that my commit was not the one merged.
That's becoming quite a frequent practice here in GitHub: the ones that have the possibility to directly merge, get the information from someone else's Pull Request and commit that information into a PR of themselves, not giving the credit to the person that took the time to share that information in the first place.
Not only that behavior is unfair and unprofessional, but it also defeats the whole purpose of the Pull Requests.

**Pull request merged**
