### PR TITLE
Added note for Win 10 Multi-session

### PR DESCRIPTION
**Pull request by cowhitley**
Added a note that calls out the fact that upgrades from Windows 10 Professional and Enterprise to Windows 10 Multi-session are not currently supported.

### CODE REVIEW

**Comment by cowhitley** [comment]
Pull request is for the following issue.

https://github.com/MicrosoftDocs/SupportArticles-docs/issues/692

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[f5b3a70](https://github.com/cowhitley/SupportArticles-docs/commits/f5b3a70a95dc53b46e4076cd237db38d192ff65b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/cowhitley/SupportArticles-docs/blob/patch-1/support/azure/virtual-machines/in-place-system-upgrade.md) | :warning:Warning | | [Details](#user-content-e8a322d0d85f59c3aa560566ecdd54ba-9c94a6fc)

<a id="e8a322d0d85f59c3aa560566ecdd54ba-9c94a6fc"></a>
### [support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/cowhitley/SupportArticles-docs/blob/patch-1/support/azure/virtual-machines/in-place-system-upgrade.md)
 - **Line 35, Column 171**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/virtual-desktop/windows-10-multisession-faq#can-i-upgrade-a-windows-10-vm-to-windows-10-enterprise-multi-session' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 35, Column 171**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/virtual-desktop/windows-10-multisession-faq#can-i-upgrade-a-windows-10-vm-to-windows-10-enterprise-multi-session' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202208231435380179-693/BuildReport?accessString=d8bafae50c6bf655614d9157846f2df389ce0de902f4fc965bf3663d2b7fd4a5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[7a96099](https://github.com/cowhitley/SupportArticles-docs/commits/7a96099f731a36575174ad1e821b174806922aca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/cowhitley/SupportArticles-docs/blob/patch-1/support/azure/virtual-machines/in-place-system-upgrade.md) | :bulb:Suggestion | | [Details](#user-content-e8a322d0d85f59c3aa560566ecdd54ba-70b25eba)

<a id="e8a322d0d85f59c3aa560566ecdd54ba-70b25eba"></a>
### [support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/cowhitley/SupportArticles-docs/blob/patch-1/support/azure/virtual-machines/in-place-system-upgrade.md)
 - **Line 35, Column 171**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/virtual-desktop/windows-10-multisession-faq#can-i-upgrade-a-windows-10-vm-to-windows-10-enterprise-multi-session' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202208231440454435-693/BuildReport?accessString=f9cdcc94eba314dc4d4e6c59081460c719033208e1476dd7752282112d7a83b4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by cowhitley** [comment]
Should also cover the following issue. https://github.com/MicrosoftDocs/SupportArticles-docs/issues/691

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[b6357c7](https://github.com/cowhitley/SupportArticles-docs/commits/b6357c74484cc296c7f0e308907ddf17b316d84e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/cowhitley/SupportArticles-docs/blob/patch-1/support/azure/virtual-machines/in-place-system-upgrade.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202208240114237124-693/BuildReport?accessString=9173978fe7a875a2d00f4f2237c817efea6952f14f63d8c8df9e61a9e2b1e734).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
