### PR TITLE
Clarified the ARM support

### PR DESCRIPTION
**Pull request by PoulChapman**
Clarified ARM support vs x64 support

### CODE REVIEW

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[c839ca0](https://github.com/PoulChapman/SupportArticles-docs/commits/c839ca06c01537365107778c2950cebe534c2870)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/developer/visualstudio/general/visual-studio-2022-unsupported-operating-systems.md](https://github.com/PoulChapman/SupportArticles-docs/blob/patch-2/support/developer/visualstudio/general/visual-studio-2022-unsupported-operating-systems.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202208311720056078-700/BuildReport?accessString=679dc64461f01a78cc365b329c800fc1d525f615629d1c9966ec9a5e47f9c2e9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[c11dfee](https://github.com/PoulChapman/SupportArticles-docs/commits/c11dfeeb404265e4c356c9e07a2112b77ffac1e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/developer/visualstudio/general/visual-studio-2022-unsupported-operating-systems.md](https://github.com/PoulChapman/SupportArticles-docs/blob/patch-2/support/developer/visualstudio/general/visual-studio-2022-unsupported-operating-systems.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202209010837356328-700/BuildReport?accessString=85c8f01d5d055fc2d459d168710ab56e0c3b94083f47d6f6de661b46cf63beb1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[17b1bf0](https://github.com/PoulChapman/SupportArticles-docs/commits/17b1bf0590a0c090d46b08bbd466c4bd9dc0eb31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/developer/visualstudio/general/visual-studio-2022-unsupported-operating-systems.md](https://github.com/PoulChapman/SupportArticles-docs/blob/patch-2/support/developer/visualstudio/general/visual-studio-2022-unsupported-operating-systems.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202209010907113554-700/BuildReport?accessString=2274923bc2d62a0a11b719f99ebb0e2feccca2cd5889395f646853d002ed4bc6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sevend2** [comment]
@PoulChapman Hi! Could you help check if we can remove the sentence "performance may not meet expectations"? If it's necessary, would it be possible to help me understand the word "performance"? (I'm not sure what the performance refers to. As you mentioned above, X64 Visual Studio 2022 is not supported on ARM operating systems. So, we don't need to talk the performance of X64 Visual Studio 2022 on ARM operating systems.) If the performance refers to other versions of Visual Studio 2022 on ARM operating systems, could you help clarify it? Looking forward to your reply! Appreciate it!

BTW, could you leave "sign-off" in the comment if it's ready to merge? Thanks.

**Comment by PoulChapman** [comment]
@sevend2 Please leave the text as I originally had it.

Performance is a standard term for developer software. MSFT uses "Arm64" not "ARM64"

X64 Visual Studio 2022 is not supported on ARM operating systems; performance may not meet expectations. Arm64 Visual Studio 2022 version 17.4 and later versions are supported only on Windows 11 on Arm.

**Comment by PoulChapman** [comment]
marking as #sign-off to incorporate my revised change (commit 4)

X64 Visual Studio 2022 is not supported on ARM operating systems; performance may not meet expectations. Arm64 Visual Studio 2022 version 17.4 and later versions are supported only on Windows 11 on Arm.

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[1c78e7e](https://github.com/PoulChapman/SupportArticles-docs/commits/1c78e7eb64182249eb86c586e633b440c0339479)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/developer/visualstudio/general/visual-studio-2022-unsupported-operating-systems.md](https://github.com/PoulChapman/SupportArticles-docs/blob/patch-2/support/developer/visualstudio/general/visual-studio-2022-unsupported-operating-systems.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202209022132148128-700/BuildReport?accessString=6a61e854ac59ea1b6ea543e66f3a0eca14cd15ef2f304d70bb8933024dd8e6d1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[bd5ef3d](https://github.com/PoulChapman/SupportArticles-docs/commits/bd5ef3da7f4a6dbaa5adb381f1f832b95a6a1b3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/developer/visualstudio/general/visual-studio-2022-unsupported-operating-systems.md](https://github.com/PoulChapman/SupportArticles-docs/blob/patch-2/support/developer/visualstudio/general/visual-studio-2022-unsupported-operating-systems.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202209050718283096-700/BuildReport?accessString=2fc2551cf3669963c60eda497d0ab9aee74d25867ee185d753f5efd295719ef0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by HaiyingYu** [comment]
@PoulChapman Merged the PR. You can create PRs in our [private repo](https://github.com/MicrosoftDocs/SupportArticles-docs-pr) to suggest content changes next time.

**Pull request merged**
