### PR TITLE
Update ribbon-issues-button-wrong-label.md

### PR DESCRIPTION
**Pull request by gaboyer**
Add a section on checking the letter casing of ribbon label IDs, as they are case-sensitive. This is in response to a related customer incident.

# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Review by brflood — APPROVED** [review]

**Comment by gaboyer** [comment]
#sign-off

**Review by aartig13 — APPROVED** [review]

**Comment by lucciz01** [comment]
Hi @gaboyer and @aartig13, the draft is ready for your final review. Feel free to let me know if it's OK to publish. Thanks!

**Comment by aartig13** [comment]
> Hi @gaboyer and @aartig13, the draft is ready for your final review. Feel free to let me know if it's OK to publish. Thanks!

Looks good to me

**Comment by gaboyer** [comment]
> Hi @gaboyer and @aartig13, the draft is ready for your final review. Feel free to let me know if it's OK to publish. Thanks!

Yes, looks fine. Thank you.

**Pull request merged**
