### PR TITLE
Update troubleshoot-win32-app-install.md

### PR DESCRIPTION
**Pull request by mackie1604**
Removing Sidecar agent requirements and add Windows requirements.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@mackie1604 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @helenclu

**Comment by PRMerger9** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger3** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@helenclu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
