### PR TITLE
Add new unattended error codes in troubleshoot-desktop-flow-run-queue-errors.md

### PR DESCRIPTION
**Pull request by lulubran**
Add UnattendedUserSessionDisconnected and UnattendedUserSessionLocked

# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Comment by lulubran** [comment]
#sign-off

**Comment by lulubran** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by lucciz01** [comment]
For creating a preview link of the changes and further discussion, I copied the changes from this PR to private PR-[5900](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/5900).

**Comment by lucciz01** [comment]
Hi @lulubran and @rpapostolis, the changes submitted in this PR were merged via PR-[5900](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/5900). So, I will close this PR. Thanks for reviewing.

**Comment by lucciz01** [comment]
Hi @lulubran and @rpapostolis, the changes submitted in this PR were merged via PR-[5900](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/5900). So, I close this PR. Thanks for reviewing.

**Pull request closed without merging**
