### PR TITLE
Update RegEx Example to include Windows Computer DisplayName

### PR DESCRIPTION
**Pull request by blakedrumm**
Assisted co-worker Joana da Rocha Carvalho (joana.carvalho@microsoft.com) with a case that required Windows Computer Display Name regular expression for multiple servers. Updated the examples to include how to write an expression for evaluating Windows Computer DisplayNames with Regular Expression.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@blakedrumm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger5** [comment]
@helenclu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@helenclu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by blakedrumm** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@blakedrumm: I'm sorry - only the author of this article, @helenclu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
