### PR TITLE
Fix issue with missing bullet and start of next section

### PR DESCRIPTION
**Pull request by blakedrumm**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@blakedrumm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@blakedrumm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@blakedrumm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@blakedrumm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@blakedrumm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@blakedrumm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by simonxjx** [comment]
@blakedrumm If your content is ready for review and merge, please type "#sign-off" in a new comment.

**Comment by blakedrumm** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@blakedrumm: I'm sorry - only the author of this article, @helenclu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger17** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger5** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by helenclu** [comment]
@blakedrumm , for tables with empty Description column, I'd suggest to remove this column. It may cause confusion.

**Comment by blakedrumm** [comment]
@helenclu you are welcome to edit the tables and remove the description column. I tried to keep it uniform for all the performance counters. But I understand where this could cause confusion.

**Comment by PRMerger-2** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by x-limitless-x** [comment]
We should leave the table column for Performance Counter

**Comment by blakedrumm** [comment]
image

The Performance Counter names should not be multi-line. The Performance Counter should be full and on a single line. It doesn't look right the way the table is formatted now: [https://docs.microsoft.com/troubleshoot/system-center/scom/troubleshoot-gray-agent-states](https://docs.microsoft.com/troubleshoot/system-center/scom/troubleshoot-gray-agent-states)

**Comment by x-limitless-x** [comment]
@simonxjx please fix these tables. It is multiple tables. The initial request I created / signed-off on had the right format for the tables.

**Comment by helenclu** [comment]
The issue has been fixed.

**Pull request merged**
