### PR TITLE
Add revert Delta Lake conversion

### PR DESCRIPTION
**Pull request by v-wendysmith**
# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Review by m-hartmann — APPROVED** [review]

**Comment by m-hartmann** [comment]
#sign-off @lucciz01 could you please merge this in private to get the article added to the CI troubleshooting content? Feel free to tag me for editorial or review comments.

**Comment by lucciz01** [comment]
> #sign-off @lucciz01 could you please merge this in private to get the article added to the CI troubleshooting content? Feel free to tag me for editorial or review comments.

Hi @m-hartmann, no problem. I'll get started on this task.

**Comment by lucciz01** [comment]
PR#[5270](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/5270) is created for this task.

**Comment by lucciz01** [comment]
Hi @v-wendysmith, after a discussion with @m-hartmann and @aartig13 in a private PR, we have decided to add this article to the core docs. Therefore, I will close this PR. Please feel free to contact me if you have any questions. Thank you!

**Pull request closed without merging**
