### PR TITLE
AB#167159: Update troubleshoot-common-blue-screen-error.md

### PR DESCRIPTION
**Pull request by pranathipanyam**
If rescue VM was created manually without the "az repair" extension, you can attempt to run the script manually by copying it from github and pasting it in the "run command" option of the rescue VM ONLY if the OS disk of VM in question is properly attached as data disk AND online. win-sacdump-on: https://raw.githubusercontent.com/Azure/repair-script-library/master/src/windows/sac-os-dump-enabler.ps1 

There is another option to capture dump which is not available on public documents. This helps when customer mannualy creates repair VM without any extension.

### CODE REVIEW

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[5894567](https://github.com/pranathipanyam/SupportArticles-docs/commits/58945674fad2e470b431a392a72bc9e75e43dea2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/virtual-machines/troubleshoot-common-blue-screen-error.md](https://github.com/pranathipanyam/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/troubleshoot-common-blue-screen-error.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202209130646543525-707/BuildReport?accessString=ed167021a7ffeddcfa603a9b4a26b3f6fdf0dc5201e57b9a646e8d01ac88c78d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by AmandaAZ** [comment]
@pranathipanyam I made editorial changes for readability and update the script URL to "https://github.com/Azure/repair-script-library/blob/master/src/windows/sac-os-dump-enabler.ps1". Could you review if they are fine? Let me know if there is any problem.

**Comment by AmandaAZ** [comment]
> @pranathipanyam I made editorial changes for readability and update the script URL to "https://github.com/Azure/repair-script-library/blob/master/src/windows/sac-os-dump-enabler.ps1". Could you review if they are fine? Let me know if there is any problem.

@pranathipanyam Could you help review my changes? Thanks.

**Comment by pranathipanyam** [comment]
Please go ahead!

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[352f7cf](https://github.com/pranathipanyam/SupportArticles-docs/commits/352f7cfabf2682fe26d0670c4ae1c5d60cfc498f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/virtual-machines/troubleshoot-common-blue-screen-error.md](https://github.com/pranathipanyam/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/troubleshoot-common-blue-screen-error.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202209150547569815-707/BuildReport?accessString=518bd628231f0d63ffbfda39ef6c921149fe740f7b8fbefe6e9966e0731218d6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[37d32de](https://github.com/pranathipanyam/SupportArticles-docs/commits/37d32deec9f0bd81293774e67bc4fbd5267c33e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/virtual-machines/troubleshoot-common-blue-screen-error.md](https://github.com/pranathipanyam/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/troubleshoot-common-blue-screen-error.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202209151229539728-707/BuildReport?accessString=a08317c5e712a73413718d92bb33ad85cd18bb9bb88e70a0b5b76d491093c72b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
