### PR TITLE
[SQL]  Updated note in uninstall SSMS article

### PR DESCRIPTION
**Pull request by markingmyname**
@ramakoni1 for awareness

### CODE REVIEW

**Comment by markingmyname** [comment]
#sign-off

**Comment by Matteo-T** [comment]
The change looks good to me.

While you are editing this page, could you fix the "Windows 2008 - 2012 R2" section? If you look at bullets 4 and 5, you'll see some unexpanded token like this:

image

**Review by Matteo-T — CHANGES_REQUESTED** [review]
If you can, please take a look at to bottom of the page:

image

**Comment by markingmyname** [comment]
@Matteo-T changes addressed.  thanks for calling this out.

**Comment by markingmyname** [comment]
#sign-off

**Comment by markingmyname** [comment]
#sign-off

**Review by ramakoni1 — APPROVED** [review]
Thank you for submitting changes.

**Pull request merged**
