### PR TITLE
Add non-customizable ribbon doc

### PR DESCRIPTION
**Pull request by brflood**
Adding a new document for non-customizable ribbon buttons.

https://dynamicscrm.visualstudio.com/OneCRM/_workitems/edit/2899594

### CODE REVIEW

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[742ca37](https://github.com/brflood/SupportArticles-docs/commits/742ca37e72d7ef252e03f0ad48094bfcfbc0dc97)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/power-platform/power-apps/create-and-use-apps/ribbon-non-customizable-buttons.md](https://github.com/brflood/SupportArticles-docs/blob/brflood-ribbon-patch1/support/power-platform/power-apps/create-and-use-apps/ribbon-non-customizable-buttons.md) | :bulb:Suggestion | | [Details](#user-content-dbd7e46deefd7ee5b09d928f3122f574-1ccb4099)
[support/power-platform/power-apps/create-and-use-apps/ribbon-issues-button-visible.md](https://github.com/brflood/SupportArticles-docs/blob/brflood-ribbon-patch1/support/power-platform/power-apps/create-and-use-apps/ribbon-issues-button-visible.md) | :white_check_mark:Succeeded | |
[support/power-platform/power-apps/toc.yml](https://github.com/brflood/SupportArticles-docs/blob/brflood-ribbon-patch1/support/power-platform/power-apps/toc.yml) | :white_check_mark:Succeeded | |

<a id="dbd7e46deefd7ee5b09d928f3122f574-1ccb4099"></a>
### [support/power-platform/power-apps/create-and-use-apps/ribbon-non-customizable-buttons.md](https://github.com/brflood/SupportArticles-docs/blob/brflood-ribbon-patch1/support/power-platform/power-apps/create-and-use-apps/ribbon-non-customizable-buttons.md)
 - **Line 16, Column 121**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/dynamics365/customer-engagement/customize/make-grids-lists-editable-custom-control' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202301062130075975-836/BuildReport?accessString=e295685d40172d7738de074720b9d7a458f57cc666b4c32f20cce7bc922c50c6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[c8c5bb7](https://github.com/brflood/SupportArticles-docs/commits/c8c5bb761b0b3a5cff2dbbce818b23f1f3b261f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/power-platform/power-apps/create-and-use-apps/ribbon-issues-button-visible.md](https://github.com/brflood/SupportArticles-docs/blob/brflood-ribbon-patch1/support/power-platform/power-apps/create-and-use-apps/ribbon-issues-button-visible.md) | :white_check_mark:Succeeded | |
[support/power-platform/power-apps/create-and-use-apps/ribbon-non-customizable-buttons.md](https://github.com/brflood/SupportArticles-docs/blob/brflood-ribbon-patch1/support/power-platform/power-apps/create-and-use-apps/ribbon-non-customizable-buttons.md) | :white_check_mark:Succeeded | |
[support/power-platform/power-apps/toc.yml](https://github.com/brflood/SupportArticles-docs/blob/brflood-ribbon-patch1/support/power-platform/power-apps/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202301062142453469-836/BuildReport?accessString=92930650d11c03487b7e2ffe006232dd411784cda291db8236b6d3449348e683).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by lucciz01** [comment]
Loop @Srihari Srinivasa for any concerns.

**Comment by lucciz01** [comment]
Loop @sriharibs-msft for any concerns.

**Comment by lucciz01** [comment]
Resubmit the changes via PR#[3702](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/3702) and close this PR.

**Pull request closed without merging**
