### PR TITLE
NDVALPHA MIGRATE CA TO ANOTHER SERVER UPDATE

### PR DESCRIPTION
**Pull request by NDVALPHA**
NDVALPHA MIGRATE CA TO ANOTHER SERVER UPDATE

### CODE REVIEW

**Comment by PRMerger16** [comment]
@NDVALPHA : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by NDVALPHA — COMMENTED** [review]
NDVALPHA UPDATED PROCEDURE ON WHAT TO WHEN MIGRATING CA TO A SERVER WITH A DIFFERENT NAME, AND WHAT TO DO WHEN PUBLISHING TEMPLATES IS NOT WORKING.

**Comment by v-lianna** [comment]
@NDVALPHA Could you let us know if the PR is ready for review or merge? Then, we will proceed to handle the changes.

**Comment by NDVALPHA** [comment]
Everything is ready.

**Comment by Deland-Han** [comment]
@NDVALPHA Thank you for the feedbacks. The article is for Windows 2000 and Windows Server 2003. Both are old Windows versions. We need to review this article and I will get back to you.

**Comment by NDVALPHA** [comment]
The procedure should apply on those OS as well. Let me know if this will be published or not.

**Comment by NDVALPHA** [comment]
Any update on this? Like I said before, I've recently tested this procedure on a Windows Server 2019 Production environment, the same steps apply.

**Comment by Deland-Han** [comment]
Thanks. @ndvalpha. I will merge this pull request.

**Comment by NDVALPHA** [comment]
Any update on this?

**Pull request merged**
