### PR TITLE
Add information for inactive actions

### PR DESCRIPTION
**Pull request by JosinaJoy**
Add troubleshooting information for actions

# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Comment by lucciz01** [comment]
Hi @JosinaJoy, I made some changes based on the suggestions from @aartig13. Now the draft is ready for your final review. Please let me know if any questions. Thanks!

**Comment by lucciz01** [comment]
Per confirmed with @JosinaJoy via Teams chat, we'll add more information to this article.

**Comment by JimDaly** [comment]
@lucciz01 
I created https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/6594 to replace this.
Can we close this and move forward on the PR on the other repo?

**Comment by lucciz01** [comment]
> @lucciz01 I created [MicrosoftDocs/SupportArticles-docs-pr#6594](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/6594) to replace this. Can we close this and move forward on the PR on the other repo?

@JimDaly, np, I'll close this PR and proceed in the private repo.

**Pull request closed without merging**
