### PR TITLE
Update azure-ad-ipv6-support.md

### PR DESCRIPTION
**Pull request by jgabbert-msft**
adds procedures customers can use to test/pilot Azure AD auth over IPv6

### CODE REVIEW

**Comment by jgabbert-msft** [comment]
@microsoft-github-policy-service agree [company="{Microsoft}"]

**Comment by jgabbert-msft** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by jgabbert-msft** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by MicrosoftGuyJFlo** [comment]
Reviewing this @DennisLee-DennisLee

**Comment by AmandaAZ** [comment]
I made the same changes in the private repo via https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/3792.

**Comment by AmandaAZ** [comment]
@MicrosoftGuyJFlo I found that you submitted the [PR 3816](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/3816) to add some sections including the "Test Azure AD authentication over IPv6" and made other changes to this article. So, I think that this PR can be closed. What do you think?

**Pull request closed without merging**
