### PR TITLE
Update dependency-availability-by-country.md

### PR DESCRIPTION
**Pull request by tiffanyyumsft**
update for latest info and added go-locals that are coming soon

# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Comment by tiffanyyumsft** [comment]
@JarrettRenshaw for review and approval

**Comment by AmandaAZ** [comment]
@tiffanyyumsft I made editorial changes in this PR. One question: You're removing the asterisk (*) for some countries/regions. So, I think that this statement "_Countries/regions with an asterisk (\*) appended have recently obtained Azure dependencies_" doesn't make sense and we can remove it. What do you think? Regarding this statement "_All solutions are working on unlocking their features in these regions. Check Microsoft Center documentations to see when specific solutions will go live for these regions._", I'm not sure it's intend only for the countries/regions with an asterisk (\*) appended or for all primary countries/regions that already have Azure dependencies availability. Could you help check if we should remove it or not?

**Comment by AmandaAZ** [comment]
> @tiffanyyumsft I made editorial changes in this PR. One question: You're removing the asterisk (*) for some countries/regions. So, I think that this statement "_Countries/regions with an asterisk (*) appended have recently obtained Azure dependencies_" doesn't make sense and we can remove it. What do you think? Regarding this statement "_All solutions are working on unlocking their features in these regions. Check Microsoft Center documentations to see when specific solutions will go live for these regions._", I'm not sure it's intend only for the countries/regions with an asterisk (*) appended or for all primary countries/regions that already have Azure dependencies availability. Could you help check if we should remove it or not?

@tiffanyyumsft Could you check my question? Thanks.

**Comment by tiffanyyumsft** [comment]
@AmandaAZ  thanks for pinging me. Yes, we can remove the "_Countries/regions with an asterisk () appended have recently obtained Azure dependencies_" . We can add that statement back in later when a new country becomes available.

"All solutions are working on unlocking their features in these regions. Check Microsoft Center documentations to see when specific solutions will go live for these regions." This was intended for the newly added regions as each solution might have a slightly different timeline of when unlocking so the guidance is to check Message Center posts for announcements regarding specific solutions and regions.  Maybe we can revise this statement to be more generic that just says "Check Microsoft Message Center posts for the most accurate timeline for region enablement for the various solutions."

**Comment by AmandaAZ** [comment]
@tiffanyyumsft Thanks for your reply. The PR is updated as you suggested and merged.

**Pull request merged**
