### PR TITLE
publish docs for TSG - investigate and fix with extension for issue of assessable value/tax information is incorrect

### PR DESCRIPTION
**Pull request by lingshf**
# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Comment by lingshf** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by lucciz01** [comment]
Hi @lingshf, for further internal review and discussion, could you summit your changes to the private repo "https://github.com/MicrosoftDocs/SupportArticles-docs-pr"? Then if the draft is ready, you can leave a "#sign-off" in a comment. After that, we'll have a triage. Feel free to let us know if any questions. Thanks!

**Comment by lingshf** [comment]
#sign-off

**Comment by lingshf** [comment]
#sign-off

**Comment by lingshf** [comment]
#sign-off

**Comment by lucciz01** [comment]
As discussed with @lingshf, I'll help create a new PR to proceed with the reviewing work in private repo.

**Pull request closed without merging**
