### PR TITLE
Create allocation-failure.md

### PR DESCRIPTION
**Pull request by surbhijain16**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@surbhijain16 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @surbhijain

**Comment by PRMerger15** [comment]
@surbhijain16 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @surbhijain

**Comment by PRMerger12** [comment]
@surbhijain16 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @surbhijain

**Comment by surbhijain16** [comment]
#sign-off

**Comment by PRMerger5** [comment]
@surbhijain16: I'm sorry - only the author of this article, @surbhijain, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger9** [comment]
Microsoft authors of articles need to make updates through the private repository, so the updates can be staged and validated by current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged. 

It's easy to access the private repo version of your articles in GitHub. Just add *-pr* to the URL, as follows: 

 &nbsp;Public repo URL: `https://github.com/MicrosoftDocs/{docs-repo}` 
 &nbsp;Private repo URL: `https://github.com/MicrosoftDocs/{docs-repo-pr}` 

 We have closed this pull request. Please resubmit the updates through the private repo. For more information, see the [contributor guide](https://docs.microsoft.com/contribute/).

**Pull request closed without merging**
