### PR TITLE
Add Set-AzureADUserPassword to scenaro table

### PR DESCRIPTION
**Pull request by tlourey**
It seems that Set-AzureADUserPassword also doesn't write-back the password like Set-MsolUserPassword. It should be added to the Scenaro table. Having one and not the other listed can cause some confusion (esp since Azure AD Powershell V2 works differently). PR has this.

### CODE REVIEW

**Comment by PRMerger5** [comment]
@tlourey : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by genlin** [comment]
@tlourey, I will check with our engineers, and get back to you.

**Comment by TLCF** [comment]
Many thanks @genlin . I wish it wasn't true as I would like the set-azureaduserpassword to write back to on prem but from my limited tested so far, it doesn't seem to be the case. Looking forwarding to seeing what they confirm

**Comment by tlourey** [comment]
Many thanks @genlin . I hope it isnt true as I would like the set-azureaduserpassword to write back to on prem but from my limited tested so far, it doesn't seem to be the case. Looking forwarding to seeing what they confirm.

**Comment by simonxjx** [comment]
The change is applied via #417. Close this one.

**Comment by tlourey** [comment]
@genlin where is the _current_ feedback location so that I can request this functionality **does** work?

**Pull request closed without merging**
