### PR TITLE
Add solution for fixing Unix/Linux Discovery Errors

### PR DESCRIPTION
**Pull request by blakedrumm**

### CODE REVIEW

**Comment by blakedrumm** [comment]
Following the information present in my blog:
[https://blakedrumm.com/blog/unix-linux-discovery-errors/](https://blakedrumm.com/blog/unix-linux-discovery-errors/)

**Comment by blakedrumm** [comment]
I think it would be helpful to include this error as well:
image

**Comment by PRMerger19** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by helenclu** [comment]
Sent email to triage team to review the changes. 

@blakedrumm , MS submitters are required to work in the private repo. Could you follow https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=main to make changes to the private repo in the future?

**Comment by AmandaAZ** [comment]
@blakedrumm The solutions are added via [private PR3214](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/3214), so we close this public PR. Thanks for your contribution.

**Pull request closed without merging**
