### PR TITLE
AB#169199: Update kerberos-protocol-registry-kdc-configuration-keys.md

### PR DESCRIPTION
**Pull request by WAftring**
- Clarifying where the time difference is permitted.
- Add additional information RE: impact of SkewTime on kerberos ticket reuse

### CODE REVIEW

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[d69e292](https://github.com/WAftring/SupportArticles-docs/commits/d69e292e7470e90e38f7e3f59e5eaba1f2b100bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/windows-server/windows-security/kerberos-protocol-registry-kdc-configuration-keys.md](https://github.com/WAftring/SupportArticles-docs/blob/patch-1/support/windows-server/windows-security/kerberos-protocol-registry-kdc-configuration-keys.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210311854305682-768/BuildReport?accessString=69b6bb02ff399925e033f1de0f9ae9df0eb2a5ece2f641d16e69211d61dca546).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by v-lianna** [comment]
@WAftring Thanks for your contribution. We will review the changes.

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[3bdadca](https://github.com/WAftring/SupportArticles-docs/commits/3bdadca78d2f91f1cbbdd9007003a9aebab63118)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/windows-server/windows-security/kerberos-protocol-registry-kdc-configuration-keys.md](https://github.com/WAftring/SupportArticles-docs/blob/patch-1/support/windows-server/windows-security/kerberos-protocol-registry-kdc-configuration-keys.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202211040728263770-768/BuildReport?accessString=097b8c26661b08956edb1185dab9de331bfd5f8763ebed3f5545dba0775eac35).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[ad58e05](https://github.com/WAftring/SupportArticles-docs/commits/ad58e05f4b1c5f7ec61137dc6c8ef2c25e17cf74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/windows-server/windows-security/kerberos-protocol-registry-kdc-configuration-keys.md](https://github.com/WAftring/SupportArticles-docs/blob/patch-1/support/windows-server/windows-security/kerberos-protocol-registry-kdc-configuration-keys.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202211040736214936-768/BuildReport?accessString=dd8c5192c7454654e34f1b9e3230b09e145bd3efbdccabe91393e2db1cb39e1c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Pull request merged**
