### PR TITLE
Update Scenario 5 to include real world events

### PR DESCRIPTION
**Pull request by blakedrumm**
The old Example Event Log Entries were not accurate. I updated to the correct Event information.

### CODE REVIEW

**Comment by PRMerger5** [comment]
@blakedrumm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by blakedrumm** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@blakedrumm: I'm sorry - only the author of this article, @helenclu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger10** [comment]
@helenclu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
