### PR TITLE
added note

### PR DESCRIPTION
**Pull request by v-pgaddala**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@v-pgaddala : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger3** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by v-pgaddala** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@v-pgaddala: I'm sorry - only the author of this article, @helenclu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
