### PR TITLE
Updating article for improvements

### PR DESCRIPTION
**Pull request by kaushika-msft**
Updates made considering user engagement and experience.

### CODE REVIEW

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[25bc744](https://github.com/MicrosoftDocs/SupportArticles-docs/commits/25bc744b54afe90199b956bb06dd7e87e4540ddb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/windows-client/system-management-components/daylight-saving-time-help-support.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/kaushika-msft-dec22improve-CI170989/support/windows-client/system-management-components/daylight-saving-time-help-support.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202212231634553022-817/BuildReport?accessString=e9a1cdb13596b4b96d7439631d0038df1e20540c73b6dd6bb7951f31786f8b20).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[34ddd80](https://github.com/MicrosoftDocs/SupportArticles-docs/commits/34ddd80cc2aae4d9d414810a8767ab9968268443)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/windows-client/system-management-components/daylight-saving-time-help-support.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/kaushika-msft-dec22improve-CI170989/support/windows-client/system-management-components/daylight-saving-time-help-support.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202212260738383318-817/BuildReport?accessString=2a5f7111a6594923143d74537cfdfc7604f9b9cacf1aa76ab4be0a3e86ed4a62).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
#sign-off

**Comment by Deland-Han** [comment]
Hi @kaushika-msft and @simonxjx, do you need me to merge the PR as the CI is in pending final review status?

**Pull request merged**
