### PR TITLE
Updating formating

### PR DESCRIPTION
**Pull request by CraigM919**
Changing formatting of schema versions to be a table format for easier reading.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@CraigM919 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by v-lianna** [comment]
@CraigM919 Could you let us know if the PR is ready for review or merge? Then, we will proceed to handle the changes.

**Comment by PRMerger7** [comment]
@CraigM919 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by CraigM919** [comment]
> @CraigM919 Could you let us know if the PR is ready for review or merge? Then, we will proceed to handle the changes.

PR is ready for review then merge.

**Comment by PRMerger14** [comment]
@Deland-Han : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Deland-Han : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
