### PR TITLE
Update password-writeback-access-rights-permissions.md

### PR DESCRIPTION
**Pull request by VMrenato**
Including needed permissions at samServer object in Active Directory. If these permissions are missing, passwordwriteback fails with access denied. Further details at
https://support.microsoft.com/en-us/topic/18fb7c57-716f-6025-4906-bc9a6f8f6158

### CODE REVIEW

**Comment by PRMerger4** [comment]
@VMrenato : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AmandaAZ** [comment]
@VMrenato If your content is ready for review and merge, type "#sign-off" in a new comment.

**Comment by PRMerger18** [comment]
@VMrenato : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DennisLee-DennisLee** [comment]
Handling this on the private repo.

**Pull request closed without merging**
