### PR TITLE
Update verify-first-party-apps-sign-in.md

### PR DESCRIPTION
**Pull request by PuravsPoint**
# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Comment by PuravsPoint** [comment]
#sign-off - Change I've made is Line 95 where I've added the App ID of 80ccca67-54bd-44ab-8625-4b79c4dc7775 which correlates to the Microsoft 365 Security and Compliance Center.

Sources where this is mentioned is https://www.rickvanrousselt.com/blog/azure-default-service-principals-reference-table/ & https://github.com/emilyvanputten/Microsoft-Owned-Enterprise-Applications/blob/main/Microsoft%20Owned%20Enterprise%20Applications%20Overview.md

It would be great if this could be updated in the official MS docs article page called "Verify first-party Microsoft applications in sign-in reports"

This is my first pull request so hopefully I've done everything right but if there's anything I should bear in mind for next time or any issues with this pull request then please let me know.

**Comment by PuravsPoint** [comment]
Hello, I've just made another commit in which I renamed "Microsoft 365 Security & Compliance Center" to "Microsoft 365 Defender" since that's the current name. Hopefully this doesn't affect the PR approval too much.

Eager to hear feedback and/or hopefully see this PR approved and the change made in the Microsoft Learn page soon, thanks!

**Comment by PuravsPoint** [comment]
image

This image shows that 80ccca67-54bd-44ab-8625-4b79c4dc7775 is the Microsoft 365 Security and Compliance Center

I'll leave it to you guys to decide to keep this name or change it to Microsoft 365 Defender if/when this change updates in the docs.

**Comment by PuravsPoint** [comment]
Hey @genlin any update on when this PR is likely to be merged please?

**Comment by PuravsPoint** [comment]
Hey @aartig13 since you recently merged a commit for this repo, are you able to provide an update on when this PR is likely to be merged or can you nudge Genlin please? He hasn't commented at all on this PR so unsure if he's seen it, I did tag him earlier too. Thanks in advance for any help.

**Comment by aartig13** [comment]
@PuravsPoint this PR is in the queue to be triaged. Tagging @JarrettRenshaw

**Comment by AmandaAZ** [comment]
@PuravsPoint This PR is being triaged. Once it's approved, we will merge it.

**Comment by PuravsPoint** [comment]
Hi @aartig13 @AmandaAZ Hope you're well. 
Any update on this PR please? 
It's been open for 3 weeks and I have provided evidence on why this change should be made. 
It would be great to have a timeline on when this is likely to be merged, thank you. 😊

**Comment by AmandaAZ** [comment]
> Hi @aartig13 @AmandaAZ Hope you're well. Any update on this PR please? It's been open for 3 weeks and I have provided evidence on why this change should be made. It would be great to have a timeline on when this is likely to be merged, thank you. 😊

@PuravsPoint Thank you for your patience. This Pull Request is still in the process of being triaged.

**Comment by AmandaAZ** [comment]
@PuravsPoint This PR is approved. I created a private [PR#5179 ](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/5179) for it and sent the article preview page to reviewers for final review. After final review is completed, I will merge it and close your PR.

**Comment by PuravsPoint** [comment]
Thank you for the positive update @AmandaAZ , look forward to the next notification about this PR being merged and closed 😊

**Comment by AmandaAZ** [comment]
@PuravsPoint The private PR #5179 is merged, so I closed this PR.

**Pull request closed without merging**
