### PR TITLE
Update segment-no-results.md

### PR DESCRIPTION
**Pull request by JimsonChalissery**
Udpating Pre-reqs... as this trouble shooting guide should NOT be used for cases where a segment that was previously refreshing successfully with members, is now not returning any members. For that customer should raise a support ticket.

### CODE REVIEW

**Comment by lucciz01** [comment]
Hi @JimsonChalissery, I made minor changes to your draft. Can you have a review? Thanks!

**Comment by lucciz01** [comment]
Hi @JimsonChalissery, I made minor changes to your draft. Can you have a review? Thanks!

**Review by JimsonChalissery — COMMENTED** [review]
Looks good to me. THnx.

**Review by ChristySu — APPROVED** [review]
Approved

**Pull request merged**
