### PR TITLE
Update set-up-troubleshoot-linked-server.md

### PR DESCRIPTION
**Pull request by asavioliMSFT**
Changing very old client Enterprise Manager to Management studio

# Pull request guidance

Thank you for your contribution. The content team is monitoring the pull requests. Once your pull request is ready for review, please add a comment such as "PR is ready for review".

### CODE REVIEW

**Comment by sevend2** [comment]
@asavioliMSFT Thanks for your contribution! Could you help update the corresponding steps to enable "Allow InProcess" option using SSMS? I didn't see the option when adding a new linked server in SSMS. Check the image below:
image
I can only see the option mentioned above when looking into the specific providers. Check the image below:
image
Looking forward to your reply. Appreciate it!

**Comment by asavioliMSFT** [comment]
@sevend2 you already found the answer. This property is changed directly on the provider. So, for example, if customers are using an Oracle provider, they just go to Linked Servers-->Providers, Find the provider they chose when then linked server was created, right click on it and set the property Allow inProcess

**Comment by sevend2** [comment]
@PiJoCoder Could you help review this update? Let me know if anything needs to be changed. Thanks.

**Review by PiJoCoder — APPROVED** [review]
Yes, this looks good.

**Pull request merged**
