### PR TITLE
Update in-place-system-upgrade.md

### PR DESCRIPTION
**Pull request by joscon**
Support for upgrades from Windows Server 2016++ are coming to Azure soon.  Making a pull request adding in the supported scenario link, removing the Server OS list and remove the email alias which should no longer be used once the article goes live.  I've put in the current working link, it will need to be revised once the content is live.  The following OS versions are still not eligible, I'm removing them from this page and asking the tech writer for the new content to add them to the new page.

- Windows Server 2012 R2 Datacenter
- Windows Server 2012 R2 Standard
- Windows Server 2012 Datacenter
- Windows Server 2012 Standard
- Windows Server 2008 R2 Datacenter
- Windows Server 2008 R2 Standard

### CODE REVIEW

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[5cbe3a0](https://github.com/joscon/SupportArticles-docs/commits/5cbe3a0fad09b61559136b9c5de2bc4d2811f119)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/joscon/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/in-place-system-upgrade.md) | :bulb:Suggestion | | [Details](#user-content-e8a322d0d85f59c3aa560566ecdd54ba-4eecaf52)

<a id="e8a322d0d85f59c3aa560566ecdd54ba-4eecaf52"></a>
### [support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/joscon/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/in-place-system-upgrade.md)
 - **Line 67, Column 177**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://review.learn.microsoft.com/en-us/azure/virtual-machines/windows-in-place-upgrade?branch=pr-en-us-222834' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202301051752347972-833/BuildReport?accessString=7ebe52842ade63e3e70b42531ee52e0385e4062d4327674cb90e4f567413beb0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by joscon** [comment]
I am making these submissions as a Microsoft employee

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[00dde1c](https://github.com/joscon/SupportArticles-docs/commits/00dde1c915089bb63b5f8caa14b837e09fe42091)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/joscon/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/in-place-system-upgrade.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202301051800385388-833/BuildReport?accessString=8c80afdd7fa0a772206e043305a12a90d1b7e192debdb36e84a665ac547815a6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by genlin** [comment]
@joscon, When the PR is ready for merge, please leave #sign-off on the comment.

**Comment by DennisLee-DennisLee** [comment]
Handling this offline...

**Pull request closed without merging**
