### PR TITLE
Added a screenshot

### PR DESCRIPTION
**Pull request by v-anesh**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@v-anesh : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@v-anesh : Thanks for your contribution! The author(s) have been notified to review your proposed change. @helenclu

**Comment by v-anesh** [comment]
#Sign-off

**Comment by PRMerger7** [comment]
@v-anesh: I'm sorry - only the author of this article, @helenclu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger17** [comment]
@helenclu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
