### PR TITLE
Update authorization-request-denied-graph-api.md

### PR DESCRIPTION
**Pull request by mahmoudmsft**
for your approval. also note that role "User Account Administrator" doesn't exist. should it be replaced with "User Administrator" ?
Thanks
Mahmoud

### CODE REVIEW

**Comment by PRMerger17** [comment]
@mahmoudmsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mahmoudmsft** [comment]
and it's not found in Azure AD role templates as well

**Comment by PRMerger16** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by simonxjx** [comment]
@mahmoudmsft , it is a role template. You can check [here](https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureaddirectoryroletemplate) for details. I have reverted the change. By the way, I also update the structure of the cmdlets.

**Comment by mahmoudmsft** [comment]
Hi @simonxjx, no its name has changed in the role template. please check following notes:

>> from article mentioned by you (output of command "Get-AzureADDirectoryRoleTemplate")
`fe930be7-5e62-47db-91af-98c3a49a38b1 User Account Administrator`

>> running same command in my azure environment:
`fe930be7-5e62-47db-91af-98c3a49a38b1 User Administrator`

there is no template role with name "User Account Administrator" anymore and also look at the GUID it's same .

i will also do a pull request for this article  [here](https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureaddirectoryroletemplate?view=azureadps-2.0) have it changed as well.

could you now approve the pull request?

Thanks

**Comment by simonxjx** [comment]
Checking.

**Comment by mahmoudmsft** [comment]
@simonxjx , my other pull request has been accepted:
https://github.com/Azure/azure-docs-powershell-azuread/pull/674#issuecomment-888862633

**Comment by genlin** [comment]
@mahmoudmsft  Thanks for the feedback. Yes, the name is changed to "User Administrator". I will merge the PR.

**Pull request merged**
