### PR TITLE
Update redirect-users-computers-containers.md

### PR DESCRIPTION
**Pull request by baardhermansen**
Removed HTML code. 
Corrected redirusr and redircmp examples.
Very minor updates of examples so they have the same appearance.

### CODE REVIEW

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[a7f35e8](https://github.com/baardhermansen/SupportArticles-docs/commits/a7f35e8f3514d7685e3af310803a7057bc417530)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/windows-server/identity/redirect-users-computers-containers.md](https://github.com/baardhermansen/SupportArticles-docs/blob/patch-1/support/windows-server/identity/redirect-users-computers-containers.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202212091809371596-806/BuildReport?accessString=b8bdf66d206bdba3806fd61a044447aaf0821d5b2a66014a73e55f029ca467b2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by v-lianna** [comment]
@baardhermansen Thanks for your contribution. We will proceed to review the changes.

**Comment by kaushika-msft** [comment]
Sign-off

**Comment by v-lianna** [comment]
@baardhermansen The changes are live at https://learn.microsoft.com/en-us/troubleshoot/windows-server/identity/redirect-users-computers-containers. This PR will be closed.

**Pull request closed without merging**
