### PR TITLE
Update troubleshoot-ssh-connection.md

### PR DESCRIPTION
**Pull request by pagienge**
Altered the serial instructions, added a run-command section.  Switched to more portable commands for both.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@pagienge : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@pagienge : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AmandaAZ** [comment]
@pagienge Thanks for your contribution. We will review the changes in the PR.

**Comment by PRMerger4** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AmandaAZ** [comment]
@pagienge I made some adjustments to your changes. Could you check if they are fine? Let me know if there are any comments or if this PR can be merged.

**Comment by pagienge** [comment]
> @pagienge I made some adjustments to your changes. Could you check if they are fine? Let me know if there are any comments or if this PR can be merged. Please double-check those commands and outputs because I don't have lab environments to test them. Thanks.

Looks good as edited, please publish!

**Comment by PRMerger9** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AmandaAZ** [comment]
@pagienge This article is republished with those changes. It will be live soon. Thanks for your contribution!

**Pull request merged**
