### PR TITLE
update chroot steps

### PR DESCRIPTION
**Pull request by pagienge**
Edited chroot steps for clarity and consistency throughout doc

### CODE REVIEW

**Comment by AmandaAZ** [comment]
@pagienge Once your content is ready for review and merge, type "#sign-off" in a new comment.

**Comment by AmandaAZ** [comment]
@pagienge Let us know if this PR  is ready for review or merge.

**Comment by pagienge** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@pagienge: I'm sorry - only the author of this article, @genlin, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by pagienge** [comment]
Looks like I don't have rights to sign-off, the author needs to do that

Paul Gienger
Microsoft Azure Linux Escalations Support
Escalation Engineer
Working Hours:
Working Days:
Email:
08:00-17:00 CST(GMT-6)
Monday-Friday
***@***.******@***.***>

If you have any questions about a case, please contact ***@***.******@***.***>
Service Dashboard<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.microsoft.com%2Fwindowsazure%2Fsupport%2Fstatus%2Fservicedashboard.aspx&data=04%7C01%7CPaul.Gienger%40microsoft.com%7Ca09a3ab99b42491aea9108d9359cf398%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637599770483042332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SVTk%2Bc0H1YEBTF9mFvAA5sbFIoYX5bTCfF4rW6aoVaw%3D&reserved=0> | Create a Case<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.microsoft.com%2Fwindowsazure%2Fsupport%2F&data=04%7C01%7CPaul.Gienger%40microsoft.com%7Ca09a3ab99b42491aea9108d9359cf398%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637599770483042332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dkV%2BLSR0dUugR0hC%2Bj9uujwtegbmyS1L0zr8z1Wq2KY%3D&reserved=0>
[MSFT_logo_Gray DE sized SIG1.png]

**Pull request merged**
