### PR TITLE
Update reset-local-password-without-agent.md

### PR DESCRIPTION
**Pull request by yuvaraj-azurevm**
We have internal documentation for offline password resets in Azure virtual machines, and the steps are effective.

# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Comment by yuvaraj-azurevm** [comment]
#sign-off

**Comment by glimoli** [comment]
When we created this article, we avoided on purpose to add the steps that this PR is asking to add as otherwise, we would be instructing customers on how to hack a VM. Don’t know if those steps should be on the public doc entirely.

**Comment by yuvaraj-azurevm** [comment]
Hello Team,

we have Public documentation, How to reset password if the guest agent is not reporting in ready state using single user mode from serial console in which we would getting into bash command and then resetting the password.

In similar way for windows if the guest agent is not reporting ready we are doing password reset using offline method
Reset a local Windows password without Azure agent - Virtual Machines | Microsoft Learn<https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/windows/reset-local-password-without-agent#detailed-steps-for-the-vm-with-resource-manager-deployment>

The underlying concept is to gain access for the VM after the password reset, since the current documentation steps doesn't work, and which made me think of updating alternative method of reseting the password .

If we believe it's a security concern then we need to remove the steps for offline reset for linux using serial console and guest agent offline method as well.

It's my thought and do correct me if I am wrong on it.

Regards,
Yuvaraj

**Comment by AmandaAZ** [comment]
@yuvaraj-azurevm I close this PR as it's declined (because it might pose a security risk). Thanks.

**Pull request closed without merging**
