### PR TITLE
Update troubleshoot-scep-certificate-profiles.md

### PR DESCRIPTION
**Pull request by cajenk**
Updating Logs for the new connector. 
This is an internal Msft Review

# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Comment by cajenk** [comment]
#sign-off

**Comment by simonxjx** [comment]
@cajenk, I made some changes, please have a review and let me know if the changes are ok. Thanks.

**Comment by cajenk** [comment]
Hi Simonx

Thanks for this prompt response.

Thanks for polishing my comments 😎

I already reviewed all the changes, and it looks good.

The only one that I maybe would have change is this one:

***@***.***

I think it is still important to highlight that we would like console logs from a Mac computer.  (and the instructions after are in reference to running that on a Mac)
You can collect console logs from a Windows devices, but these logs don’t have the same information that the logs collected from a Mac would.

In the future I would like to do further changes to this article, it is very outdated.

We have many of the troubleshooting steps in our Wiki. (internal) .

Even the picture at the beginning (the Flow) is incorrect now; but those changes requires time and It is more important that at least people know what logs to collect than the rest.

Best regards,

Carlos Jenkins
Intune Support Escalation Engineer
Microsoft Intune - SCIM
Office: +1 (980) 776-7689
Email: ***@***.******@***.***>
Working Hours: Monday to Friday 9:30 AM – 6:00 PM EST

Need help outside of my working hours?
Manager: Sara Hancock, ***@***.******@***.***>

[Image result for microsoft logo]
[A black background with white text  Description automatically generated]

**Comment by simonxjx** [comment]
@cajenk, I have made the change. Thanks.

**Review by kaushika-msft — APPROVED** [review]

**Pull request merged**
