### PR TITLE
fix "applies to" with supported OS Level [tested]

### PR DESCRIPTION
**Pull request by DevOpsStyle**
Good Morning Team,

Recently I followed Customers with this type of Migration with Different OS Level (2008 R2, 2016, 2019) and in my personal lab (2012 - 2012 R2). The steps works fine also for these operating system.

Thank you

### CODE REVIEW

**Comment by PRMerger13** [comment]
@DevOpsStyle : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by DevOpsStyle — COMMENTED** [review]
edited "Applies to" row

**Comment by v-lianna** [comment]
@DevOpsStyle Could you let us know if the PR is ready for review or merge? Then, we will proceed to handle the changes.

**Comment by DevOpsStyle** [comment]
> @DevOpsStyle Could you let us know if the PR is ready for review or merge? Then, we will proceed to handle the changes.

All is ready. Thank You

**Pull request merged**
