### PR TITLE
Update Win32 App install to reflect collect diagnostic

### PR DESCRIPTION
**Pull request by mackie1604**
Updating logs to diagnostics and other changes.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@mackie1604 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by simonxjx** [comment]
@mackie1604 If the PR is ready for merge, can you type "#sign-off" in a comment?

**Comment by mackie1604** [comment]
#sign-off

**Comment by PRMerger4** [comment]
@mackie1604: I'm sorry - only the author of this article, @helenclu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mackie1604** [comment]
@simonxjx can you publish?  It won't let me do it.

**Comment by PRMerger12** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by simonxjx** [comment]
@mackie1604 The PR is merged. Thanks.

**Pull request merged**
