### PR TITLE
Test connectivity and telemetry ingestion using PowerShell or curl clients

### PR DESCRIPTION
**Pull request by Nawrock**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@Nawrock : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@Nawrock : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[9b4d5c8](https://github.com/Nawrock/SupportArticles-docs/commits/9b4d5c8e48a9aab24afac8487f3956f3fcf71bb3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md](https://github.com/Nawrock/SupportArticles-docs/blob/test-connectivity/support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md) | :warning:Warning | | [Details](#user-content-89a410ee5c02b10d2dd1db62b2d34b6f-87c3c061)

<a id="89a410ee5c02b10d2dd1db62b2d34b6f-87c3c061"></a>
### [support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md](https://github.com/Nawrock/SupportArticles-docs/blob/test-connectivity/support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md)
 - **Line 2, Column 1**: **[Warning: author-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````
 - **Line 302, Column 205**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#tls-dtls-and-ssl-protocol-version-settings' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 304, Column 141**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````
 - **Line 302, Column 205**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#tls-dtls-and-ssl-protocol-version-settings' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 304, Column 141**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202208041643585460-672/BuildReport?accessString=c012786424a30a305750fba8e0d90cac83ee64bc17e45f2ff237edf7ff212073).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[9b11c55](https://github.com/Nawrock/SupportArticles-docs/commits/9b11c556b494b9f1d556337423daea9c25b3f928)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md](https://github.com/Nawrock/SupportArticles-docs/blob/test-connectivity/support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md) | :warning:Warning | | [Details](#user-content-89a410ee5c02b10d2dd1db62b2d34b6f-ebc60a69)

<a id="89a410ee5c02b10d2dd1db62b2d34b6f-ebc60a69"></a>
### [support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md](https://github.com/Nawrock/SupportArticles-docs/blob/test-connectivity/support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md)
 - **Line 301, Column 205**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#tls-dtls-and-ssl-protocol-version-settings' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 303, Column 141**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 6, Column 12**: **[Suggestion: ms-author-invalid - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'todd.foust' is not a valid Microsoft alias.`````
 - **Line 301, Column 205**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#tls-dtls-and-ssl-protocol-version-settings' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 303, Column 141**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202208041645316680-672/BuildReport?accessString=ed4c2c20c4982277a35c3aa7b9a8885bca9a3f31de2a86ae9a3a1ed0d92af561).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by PRMerger17** [comment]
@Nawrock : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[96db8cb](https://github.com/Nawrock/SupportArticles-docs/commits/96db8cbf226c02b0ee4999166375d57eec1fc995)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md](https://github.com/Nawrock/SupportArticles-docs/blob/test-connectivity/support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md) | :warning:Warning | | [Details](#user-content-89a410ee5c02b10d2dd1db62b2d34b6f-1b6c3a8f)

<a id="89a410ee5c02b10d2dd1db62b2d34b6f-1b6c3a8f"></a>
### [support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md](https://github.com/Nawrock/SupportArticles-docs/blob/test-connectivity/support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md)
 - **Line 7, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'todd.foust' is not a valid GitHub ID.`````
 - **Line 302, Column 205**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'windowsserverdocs/WindowsServerDocs/security/tls/tls-registry-settings.md'.`````
 - **Line 304, Column 141**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'docs/docs/framework/network-programming/tls.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202208051551141855-672/BuildReport?accessString=5cd623935434290480a1da6dbf940960b86e8003f0d976c8badc0bf6ecda62f9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by PRMerger7** [comment]
@Nawrock : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[6189f0c](https://github.com/Nawrock/SupportArticles-docs/commits/6189f0c770bd30ce6f87572260290872b9b3e889)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md](https://github.com/Nawrock/SupportArticles-docs/blob/test-connectivity/support/azure/azure-monitor/app-insights/test-connectivity-troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202208051559395404-672/BuildReport?accessString=be1a76dd6be3b46cd8ea21f5766a1c1a68985475c0e03604d46451923484cbf9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[6189f0c](https://github.com/Nawrock/SupportArticles-docs/commits/6189f0c770bd30ce6f87572260290872b9b3e889)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0a36189a)

<a id="0a36189a"></a>
###
 - **[Error: GitBranchDeletedOrForcePushed]** `````Cannot sync git repo to specified commit because branch test-connectivity has been deleted or has been force pushed`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202208051631219678-672/BuildReport?accessString=7c45ebdc67c1534640ace708367ea9cfaa86872057b6a168c0e640ec5eee3476).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
