### PR TITLE
Remove known issues for OT Python

### PR DESCRIPTION
**Pull request by lzchen**

### CODE REVIEW

**Comment by lzchen** [comment]
#sign-off

**Comment by lzchen** [comment]
@toddfoust  @genlin 

Can I get an approval for this?

**Comment by toddfoust** [comment]
We'll need @genlin to approve. This change is to remove known issues that have been fixed by latest SDK, so they are no longer 'issues', so removing the doc references here. Should be good to go here.

**Comment by genlin** [comment]
@lzchen @toddfoust  Thanks for the update. Will merge the PR.

**Pull request merged**
