### PR TITLE
Update read-small-memory-dump-file.md

### PR DESCRIPTION
**Pull request by RAJU2529**
Replaced small letter to capital letter

### CODE REVIEW

**Comment by v-tappelgate** [comment]
@RAJU2529,
I've migrated these changes to our internal repo, so the article can get some style and coding updates in addition to these changes. However, I do have a question regarding line 40. Are you certain about changing ETHREAD to THREAD? 
The article [Windows kernel opaque structures](https://learn.microsoft.com/windows-hardware/drivers/kernel/eprocess#ethread) describes EPROCESS and ETHREAD, but there's no mention of THREAD.
Please confirm the change.

**Comment by RAJU2529** [comment]
@v-tappelgate  Yes sir I changed ETHREAD TO THREAD  one time only, I thought it's typo mistake.

**Comment by v-tappelgate** [comment]
The changes have been published from the private/internal PR (
[v-tappelgate-CI-181941](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/commit/bcf2a458a0b62011cc98edaf602499d2a8e0be48)https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/5031[)](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/commit/bcf2a458a0b62011cc98edaf602499d2a8e0be48))

**Comment by v-lianna** [comment]
@RAJU2529 The changes are live. This PR will be closed.

**Pull request closed without merging**
