### PR TITLE
Docs 2024 review: http-status-code.md

### PR DESCRIPTION
**Pull request by paulcociuba**
Changes made:
- removed obsolete versions of IIS
- re-formulated some of the acronyms in the article.

# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Comment by HaiyingYu** [comment]
Hi @paulcociuba, thanks for reviewing and updating the article. Please type "#sign-off" in a new comment when you complete your changes. Once you sign off the PR, we will process it in our [private repo](https://github.com/MicrosoftDocs/SupportArticles-docs-pr) for further internal discussions. And you can create PRs in the private repository directly in the future. The public repository is for external users.

**Comment by sevend2** [comment]
@paulcociuba I also made some updates in a new commit. Could you help check it out? Let me know if you have any suggestions. Feel free to leave "sign-off" if it's ok to proceed. Thanks.

**Comment by paulcociuba** [comment]
#sign-off

**Comment by sevend2** [comment]
Here is a private PR https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/7517 to replace this Public PR

**Pull request closed without merging**
