### PR TITLE
Create visual-studio-2022-unsupported-operating-systems

### PR DESCRIPTION
**Pull request by PoulChapman**
draft page for use with the VS 2022 unsupported OS dialog

Need to run this through various Product Team reviews before the PR is merged.

### CODE REVIEW

**Review by dzsquared — APPROVED** [review]

**Comment by PoulChapman** [comment]
this is ready to publish. Note that it's not in the TOC at this time. We'll add it to the TOC once Preview 4 ships.

#sign-off

**Comment by PRMerger19** [comment]
@PoulChapman: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PoulChapman** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@PoulChapman: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PoulChapman** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@PoulChapman: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request closed without merging**
