### PR TITLE
Update error-code-requestdisallowedbypolicy.md

### PR DESCRIPTION
**Pull request by abarqawi**
Adding 
1-where to find the policy name or assignment in the error msg RequestDisallowedByPolicy

2-also how to bring cluster to success state after fixing the policy

# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Review by abarqawi — COMMENTED** [review]
fixing url

**Comment by AmandaAZ** [comment]
@abarqawi I made editorial changes in this PR for better readability. Regarding 'The name of a policy assignment or definition is the last segment of the `id` string.", what/where is the id? In this article, it isn't currently displayed in the error message.

**Comment by abarqawi** [comment]
Yes @AmandaAZ for rge policy assignment name ,but the thing the error msg is very big angld better ro clarify to cx

**Comment by AmandaAZ** [comment]
> segment

@abarqawi OK. In this case, I think that we could say "The name of a policy assignment or definition is the last segment of **the `id` string shown in the error message**" instead of writing the detailed error and id string in the article.

**Comment by abarqawi** [comment]
Ok

**Pull request merged**
