### PR TITLE
Update in-place-system-upgrade.md

### PR DESCRIPTION
**Pull request by joscon**
Removing the Windows Server content from this article as well as the special alias.  We have a new Windows Server article for in-place upgrade.  Can we add a section for customers that points to it instead: https://learn.microsoft.com/en-us/azure/virtual-machines/windows-in-place-upgrade 

We have moved the unsupported Windows Server versions into this article and are killing off the alias.  I tried to submit this internally but it wouldnt let me so ping me with any questions (joscon)

### CODE REVIEW

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[d0389a2](https://github.com/joscon/SupportArticles-docs/commits/d0389a2804b2413a755209d74b79900db3de1504)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/virtual-machines/in-place-system-upgrade.md](https://github.com/joscon/SupportArticles-docs/blob/patch-4/support/azure/virtual-machines/in-place-system-upgrade.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202301172334362255-870/BuildReport?accessString=9c3672be0c5d3057085e2c2b28055402588ccebf3eba8008cf3893c70481f0de).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by AmandaAZ** [comment]
@joscon I want to confirm if Windows Server 2012 R2, Windows Server 2012 and Windows Server 2008 R2 need to be removed. I find these Windows Server versions remain in another PR https://github.com/MicrosoftDocs/SupportArticles-docs/pull/833 that you submitted earlier. This is the latest version of in-place-system-upgrade.md: https://learn.microsoft.com/en-US/troubleshoot/azure/virtual-machines/in-place-system-upgrade

image

**Comment by joscon** [comment]
Thanks Amanda, this is being taken care of via another thread so you can ignore this PR for now.  I didn't realize 833 was open and created PR 870 so I caused a bunch of confusion.

**Comment by AmandaAZ** [comment]
@joscon Thanks for your explanation. I will close this PR.

**Pull request closed without merging**
