### PR TITLE
Update swap-file-not-recreated-linux-vm-restart.md

### PR DESCRIPTION
**Pull request by saimsh-msft**
swap is not triggered during soft reboot and therefore added changes  under per-boot script

### CODE REVIEW

**Comment by PRMerger13** [comment]
@saimsh-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change. @genli

**Comment by genlin** [comment]
@saimsh-msft Thanks for helping to improve the document.

**Comment by saimsh-msft** [comment]
@genlin 
i see that the changes are still not merged. Could you provide an ETA here? 
Thanks, 
Saim

**Comment by genlin** [comment]
@saimsh-msft The PR was merged. Thanks!

**Pull request merged**
