### PR TITLE
Update note for custom storage account

### PR DESCRIPTION
**Pull request by wilfriedwoivre**
Update note for prerequisites for serial console. 
Storage must be accessible from all networks like indicate in FAQ for Serial console https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-errors#common-errors

### CODE REVIEW

**Comment by PRMerger20** [comment]
@wilfriedwoivre : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by charotAmine** [comment]
+1 nice one

**Comment by PRMerger6** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by wilfriedwoivre** [comment]
Thanks, yes it's more clear !

**Comment by PRMerger6** [comment]
@genlin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
