### PR TITLE
AB#168029: Update verify-if-web-service-is-correct.md

### PR DESCRIPTION
**Pull request by Dalbau**
Updated article

### CODE REVIEW

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[36a8ceb](https://github.com/Dalbau/SupportArticles-docs/commits/36a8ceb98172676f60dcc5466f6fea1b85efc187)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/dynamics/gp/verify-if-web-service-is-correct.md](https://github.com/Dalbau/SupportArticles-docs/blob/patch-2/support/dynamics/gp/verify-if-web-service-is-correct.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210032044592407-740/BuildReport?accessString=3d61dc336d35a25705f9ef7e416b2fc0085a03c1850a9e65d739482414bbe5f3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[422ba0f](https://github.com/Dalbau/SupportArticles-docs/commits/422ba0feb75dcfc498a09384629ffa4c1b479f83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/dynamics/gp/verify-if-web-service-is-correct.md](https://github.com/Dalbau/SupportArticles-docs/blob/patch-2/support/dynamics/gp/verify-if-web-service-is-correct.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210080530160376-740/BuildReport?accessString=233005d612fa6b770847e0a9a2f7687f7c135dc264eb49bc2c5f57227886596c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[219abbd](https://github.com/Dalbau/SupportArticles-docs/commits/219abbd73417ba992a3809074cdae05b7941236a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/dynamics/gp/verify-if-web-service-is-correct.md](https://github.com/Dalbau/SupportArticles-docs/blob/patch-2/support/dynamics/gp/verify-if-web-service-is-correct.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210080642286961-740/BuildReport?accessString=9280de7059d596aaa684e44c4abd1ceec10b044046b6adccfe351976006b10dc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[3205b61](https://github.com/Dalbau/SupportArticles-docs/commits/3205b6159ccbd0ce5bd776e8c404971d72284ee6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/dynamics/gp/verify-if-web-service-is-correct.md](https://github.com/Dalbau/SupportArticles-docs/blob/patch-2/support/dynamics/gp/verify-if-web-service-is-correct.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210080725119794-740/BuildReport?accessString=934e2f1eb605ff12c8359b8601406eee736e644f8bd1250d0f2e9497e9c570f5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by lucciz01** [comment]
Per offline sync in email with @Dalbau, this PR is ready to merge.

**Pull request merged**
