### PR TITLE
Replace with a better method to delete duplicates

### PR DESCRIPTION
**Pull request by EitanBlumin**
Replace with a better method to delete duplicates

### CODE REVIEW

**Comment by ramakoni1** [comment]
Hi Eitan, 
Thank you for submitting this PR, We are reviewing this further internally and will update this thread in the next few days.
Regards.
Ramu.

**Comment by PiJoCoder** [comment]
Thanks for the submission Eitan - your query does offer a more elegant solution. 
A few suggestions:

1. Could we also add the create table and a few inserts at the beginning to make this example self-contained

create table original_table (key_value int )

insert into original_table values (1)
insert into original_table values (1)
insert into original_table values (1)


insert into original_table values (2)
insert into original_table values (2)
insert into original_table values (2)
insert into original_table values (2)

2. Could we potentially leave both solutions in the article - as I believe this KB was originally written way before the times of ROW_NUMBER() and someone could take advantage of the older method. Leave the new proposed one as Method 1 and the older one as Method 2.

Thank you

**Comment by EitanBlumin** [comment]
Thanks for the suggestions @PiJoCoder .
I committed a few more changes.
Can you please review?

**Comment by PiJoCoder** [comment]
Thanks @EitanBlumin . @ramakoni1 , feel free to make a call on the structure of the KB - keeping Summary and More Information as the standard KB format.
Thank you, @EitanBlumin  for your contribution. Keep them coming.

**Comment by EitanBlumin** [comment]
I sent another commit with the Summary and More information headings back.
I restructured the page a bit to make more sense with the KB headings.

**Comment by ramakoni1** [comment]
@EitanBlumin  and @PiJoCoder , thank you both for your contributions - our content team will review these further and merge into public branch in the next few days.

**Comment by ramakoni1** [comment]
Sorry for the delays on this. We are still working on these. Please give us few more days to merge this..

**Comment by PRMerger13** [comment]
@przlplx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@HaiyingYu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@HaiyingYu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PiJoCoder** [comment]
This is live now! Thanks everyone for contribution. @EitanBlumin thank you!

**Pull request merged**
