### PR TITLE
Update resource-domain-changes.md

### PR DESCRIPTION
**Pull request by Yupiter2005**
Updating as per CI 161612 follow up after 2203 release.
Also adding a new scenario that wasn't covered before for consideration.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@Yupiter2005 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by simonxjx** [comment]
@Yupiter2005 If the PR is ready for merge, can you type "#sign-off" in a comment?

**Comment by Yupiter2005** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@Yupiter2005: I'm sorry - only the author of this article, @helenclu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger9** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by simonxjx** [comment]
@Yupiter2005 The PR is merged. Thanks.

**Pull request merged**
