### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by v-chgri**
# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Comment by josaw1** [comment]
#sign-off

**Comment by lucciz01** [comment]
Hi @josaw1 and @v-chgri, thanks for the draft. I'll get started on this task and will let you know once it's ready.

**Comment by lucciz01** [comment]
Hi @josaw1 and @v-chgri, this PR is ready for your final review.

**Comment by josaw1** [comment]
#sign-off 
@lucciz01 please go ahead and publish. Thanks.

**Comment by bstorie** [comment]
#sign-off agreed I see no issue here.

**Comment by lucciz01** [comment]
Thanks for reviewing @josaw1 @bstorie, the article is public at: https://learn.microsoft.com/en-us/troubleshoot/dynamics-365/commerce/pricing-discounts-taxes/price-track-issues.

**Pull request merged**
