### PR TITLE
Update dependency-availability-by-country.md

### PR DESCRIPTION
**Pull request by tiffanyyumsft**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@tiffanyyumsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AmandaAZ** [comment]
@tiffanyyumsft once your content is ready for review and merge, type "#sign-off" in a new comment.

**Comment by tiffanyyumsft** [comment]
#sign-off

**Comment by PRMerger4** [comment]
@tiffanyyumsft: I'm sorry - only the author of this article, @genlin, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger4** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AmandaAZ** [comment]
@tiffanyyumsft The "#sign-off" isn't limited to the author of this article. You can also type "#sign-off" to let us know your change is ready for review and merge. In addition, I made minor change such as change the note format. Let me know if there is any problem.

**Comment by tiffanyyumsft** [comment]
@AmandaAZ thanks for these changes. The changes look good to me. You've got my #signoff

**Comment by AmandaAZ** [comment]
@tiffanyyumsft The article is republished with the necessary changes. Thanks for your contribution.

**Comment by AmandaAZ** [comment]
@tiffanyyumsft The changes take effect. You can check them again from [the article](https://docs.microsoft.com/en-us/troubleshoot/azure/general/dependency-availability-by-country).

**Pull request merged**
