### PR TITLE
Update client-ip-address-cannot-access-api-server.md

### PR DESCRIPTION
**Pull request by jaewonparkalexander**
Update client-ip-address-cannot-access-api-server.md. Also, uploaded and reflected png files for more information.

### CODE REVIEW

**Comment by jaewonparkalexander** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by jaewonparkalexander** [comment]
Closing it due to the conflicts.

**Comment by jaewonparkalexander** [comment]
Fixed the conflicts and waiting for the reflection.

**Comment by AmandaAZ** [comment]
The private PR#7315 is merged, so I closed the public PR#1615.

**Pull request closed without merging**
