### PR TITLE
fixed missing curly brace in example

### PR DESCRIPTION
**Pull request by lubomirjurukov**
I found this support article through a web search and noticed missing curly brace in the given example and misleading formatting

### CODE REVIEW

**Comment by PRMerger20** [comment]
@lubomirjurukov : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sevend2** [comment]
@lubomirjurukov Could you help sign off the PR if it's ready for review? BTW, could you help double check to make sure the code block is working well because we don't have a development environment to test it. Thanks.

**Comment by lubomirjurukov** [comment]
Hello I checked the code example its working well. #sign-off

**Comment by PRMerger15** [comment]
@lubomirjurukov: I'm sorry - only the author of this article, @HaiyingYu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by HaiyingYu** [comment]
@lubomirjurukov Thanks for your contribution! Will merge the PR.

**Pull request merged**
