### PR TITLE
Updated script for best practices

### PR DESCRIPTION
**Pull request by TheGitHubBro**
Update decline script to conform with PowerShell best practices and would like to PR it back to the community.

### CODE REVIEW

**Comment by PRMerger5** [comment]
@TheGitHubBro : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@TheGitHubBro : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@TheGitHubBro : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@TheGitHubBro : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
