### PR TITLE
Added basic troubleshooting steps for AKS cluster Start operations

### PR DESCRIPTION
**Pull request by jovieir**
Updated the landing page with additional start operations card + linked common issues.

This effort was a part of CRUD Ambassadors, WI: https://supportability.visualstudio.com/AzureContainers/_workitems/edit/57316

# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Comment by jovieir** [comment]
#sign-off

**Comment by jovieir** [comment]
Adding ms.subservice to taxonomy

**Comment by AmandaAZ** [comment]
@jovieir If you finish changes in this PR, type "ready for review" in a new comment. Then, we will proceed.

**Comment by jovieir** [comment]
ready for review

**Comment by AmandaAZ** [comment]
@jovieir The private [PR#5433](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/5433) that includes the same changes with PR#1340 is merged, so I closed this PR.

**Pull request closed without merging**
