### PR TITLE
Update faqs-app-service-linux.yml

### PR DESCRIPTION
**Pull request by Kendubu1**
Adding recommendations & clarifications around host disk space & the "no space left on device" exception
Reviewed w/ @btardif internally

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Kendubu1 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AmandaAZ** [comment]
@Kendubu1 if your content is ready for review and merge, type "#sign-off" in a new comment.

**Comment by PRMerger8** [comment]
@Kendubu1 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Kendubu1** [comment]
Updated hyperlink to remove /en-us/ segments

**Review by btardif — APPROVED** [review]
looks good 👍🏽

**Comment by btardif** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@btardif: I'm sorry - only the author of this article, @genlin, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by AmandaAZ** [comment]
@Kendubu1 @btardif thanks for your contribution. We will review your content and make the necessary updates.

**Comment by PRMerger8** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AmandaAZ** [comment]
@Kendubu1 I made minor changes. Let me know if there is any problem.

**Comment by PRMerger3** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Kendubu1 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Kendubu1** [comment]
Looks good @AmandaAZ - I suppose 'data' can be both singular & plural 😆
I made a small edit for readability

**Comment by AmandaAZ** [comment]
@Kendubu1 The article is republished with the necessary changes. Thanks for your contribution.

**Comment by btardif** [comment]
This should help mitigate: 
https://github.com/MicrosoftDocs/azure-docs/issues/83385

**Pull request merged**
