### PR TITLE
Remove escape of underscore in service file

### PR DESCRIPTION
**Pull request by lheimbs**
Escaping the underscores in service files is not necessary

### CODE REVIEW

**Comment by sevend2** [comment]
@lheimbs Hi, could you sign off the PR if it's ready for review? Thanks.

**Comment by lheimbs** [comment]
#sign-off

**Comment by PRMerger3** [comment]
@lheimbs: I'm sorry - only the author of this article, @ahmetmithat, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by HaiyingYu** [comment]
@lheimbs Thanks for your contribution! Will merge the PR.

**Pull request merged**
