### PR TITLE
Edited SharePoint site not listed

### PR DESCRIPTION
**Pull request by kisubedi**
Connectors other than SharePoint also are experiencing similar issue of not loading the dropdown items.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@kisubedi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@lucciz01 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by lucciz01** [comment]
@kisubedi, hi kisubedi, I made some changes to this article, especially for the Resolution section. Could you have double-check and sign off the article if the changes are ok? And one more question, shall we also need to update the Heading of this article, for example, from "SharePoint site isn't listed in a trigger or an action in Microsoft Flow" to "Dropdown list does not load items in a trigger or an action in Microsoft Flow"? If the heading needs a change, I think we should also update the MD file name.

**Comment by kisubedi** [comment]
@lucciz01 updated. :)

**Comment by PRMerger17** [comment]
@lucciz01 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by lucciz01** [comment]
@kisubedi, hi Kishor, I made a redirection for this article and also update the TOC. Could you sign off the article if the changes are ok? Thanks.

**Review by ChristySu — APPROVED** [review]
Approved.

**Comment by lucciz01** [comment]
Loop @ChristySu here.

**Review by ChristySu — APPROVED** [review]
Approved

**Comment by lucciz01** [comment]
@kisubedi, hi Kisubedi, the article is live. The link is: https://docs.microsoft.com/troubleshoot/power-platform/power-automate/dropdown-does-not-list-items-in-trigger-or-action.

**Pull request merged**
