### PR TITLE
AB#168238: Adding VNet TSG for Windows and Linux Apps 

### PR DESCRIPTION
**Pull request by hepiet**
Adding VNet TSG for Windows And Linux Apps and Pictures for TSG's.

### CODE REVIEW

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[d246544](https://github.com/hepiet/SupportArticles-docs/commits/d246544142a5def31fd2b8ae6ef3f3ada7be1e42)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/app-service/troubleshoot-vnet-integration-apps.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/troubleshoot-vnet-integration-apps.md) | :warning:Warning | | [Details](#user-content-0a4c7560f1d62df072122d865a89cc05-16d75203)
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter01.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter01.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter02.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter02.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter03.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter03.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter04.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter04.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter05.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter05.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/privateipkudu.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/privateipkudu.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/privateiplinux.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/privateiplinux.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/privateipwindows.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/privateipwindows.png) | :white_check_mark:Succeeded | |

<a id="0a4c7560f1d62df072122d865a89cc05-16d75203"></a>
### [support/azure/app-service/troubleshoot-vnet-integration-apps.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/troubleshoot-vnet-integration-apps.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 7, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'HelenePietz-MS' is not a valid GitHub ID.`````
 - **Line 51, Column 148**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../articles/app-service/quickstart-custom-container.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210141543372161-751/BuildReport?accessString=3ba80d7c942a66a9ad9f3fb732854b22c1e715e23a8f58b7c81aaf822ed329e1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[f3a39d5](https://github.com/hepiet/SupportArticles-docs/commits/f3a39d58f0f7a62946cc01e7e18d7e8f9e5ca5e4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/app-service/articles/quickstart-custom-container.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/articles/quickstart-custom-container.md) | :x:Error | | [Details](#user-content-5d316ac24a2ec10b36bb5a760a6777f9-ef3d1b28)
[support/azure/app-service/troubleshoot-vnet-integration-apps.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/troubleshoot-vnet-integration-apps.md) | :warning:Warning | | [Details](#user-content-0a4c7560f1d62df072122d865a89cc05-ef3d1b28)

<a id="5d316ac24a2ec10b36bb5a760a6777f9-ef3d1b28"></a>
### [support/azure/app-service/articles/quickstart-custom-container.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/articles/quickstart-custom-container.md)
 - **Line 15, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-visual-studio-pivot.md'.`````
 - **Line 19, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-linux-visual-studio-code-pivot.md'.`````
 - **Line 23, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-linux-azure-portal-pivot.md'.`````
 - **Line 27, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-azure-portal-pivot.md'.`````
 - **Line 31, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-powershell-pivot.md'.`````
 - **Line 35, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-cli-pivot.md'.`````
 - **Line 2, Column 1**: **[Warning: ms-prod-or-service-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="0a4c7560f1d62df072122d865a89cc05-ef3d1b28"></a>
### [support/azure/app-service/troubleshoot-vnet-integration-apps.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/troubleshoot-vnet-integration-apps.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 7, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'HelenePietz-MS' is not a valid GitHub ID.`````
 - **Line 51, Column 148**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../articles/app-service/quickstart-custom-container.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210142227595625-751/BuildReport?accessString=a2fbac976da331919e23126108eb660eae5a80b6737d691e8f2821c9f7b60c62).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[51ba2ba](https://github.com/hepiet/SupportArticles-docs/commits/51ba2ba858a1c2f670ce06b5c8a90b96f1096eb5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/app-service/articles/quickstart-custom-container.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/articles/quickstart-custom-container.md) | :x:Error | | [Details](#user-content-5d316ac24a2ec10b36bb5a760a6777f9-ba4861ea)
[support/azure/app-service/troubleshoot-vnet-integration-apps.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/troubleshoot-vnet-integration-apps.md) | :warning:Warning | | [Details](#user-content-0a4c7560f1d62df072122d865a89cc05-ba4861ea)

<a id="5d316ac24a2ec10b36bb5a760a6777f9-ba4861ea"></a>
### [support/azure/app-service/articles/quickstart-custom-container.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/articles/quickstart-custom-container.md)
 - **Line 15, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-visual-studio-pivot.md'.`````
 - **Line 19, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-linux-visual-studio-code-pivot.md'.`````
 - **Line 23, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-linux-azure-portal-pivot.md'.`````
 - **Line 27, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-azure-portal-pivot.md'.`````
 - **Line 31, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-powershell-pivot.md'.`````
 - **Line 35, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-cli-pivot.md'.`````
 - **Line 2, Column 1**: **[Warning: ms-prod-or-service-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="0a4c7560f1d62df072122d865a89cc05-ba4861ea"></a>
### [support/azure/app-service/troubleshoot-vnet-integration-apps.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/troubleshoot-vnet-integration-apps.md)
 - **Line 50, Column 148**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../articles/app-service/quickstart-custom-container.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210142232247265-751/BuildReport?accessString=d2278de60d8135461ca996afdcf346197bccadec16e2fcea5026c4324439b450).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[4b566eb](https://github.com/hepiet/SupportArticles-docs/commits/4b566eb5e4dfe8da67766b171f87125fd0f65958)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/articles/quickstart-custom-container.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/articles/quickstart-custom-container.md) | :x:Error | | [Details](#user-content-4b70554451b6c5d55adbfcc1edcc6887-8e6b2679)
[support/azure/app-service/troubleshoot-vnet-integration-apps.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/troubleshoot-vnet-integration-apps.md) | :warning:Warning | | [Details](#user-content-0a4c7560f1d62df072122d865a89cc05-8e6b2679)

<a id="4b70554451b6c5d55adbfcc1edcc6887-8e6b2679"></a>
### [support/azure/articles/quickstart-custom-container.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/articles/quickstart-custom-container.md)
 - **Line 15, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-visual-studio-pivot.md'.`````
 - **Line 19, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-linux-visual-studio-code-pivot.md'.`````
 - **Line 23, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-linux-azure-portal-pivot.md'.`````
 - **Line 27, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-azure-portal-pivot.md'.`````
 - **Line 31, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-powershell-pivot.md'.`````
 - **Line 35, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-cli-pivot.md'.`````
 - **Line 2, Column 1**: **[Warning: ms-prod-or-service-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="0a4c7560f1d62df072122d865a89cc05-8e6b2679"></a>
### [support/azure/app-service/troubleshoot-vnet-integration-apps.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/troubleshoot-vnet-integration-apps.md)
 - **Line 50, Column 148**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../articles/app-service/quickstart-custom-container.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210142237413311-751/BuildReport?accessString=241ac32507e6c76475e2cd3a1c63f3e8bb4675286ced6a0a5d7a699519a3746e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[68952ab](https://github.com/hepiet/SupportArticles-docs/commits/68952ab3bd808f51a52030ab082210c8980cc41e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/articles/appservice/quickstart-custom-container.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/articles/appservice/quickstart-custom-container.md) | :x:Error | | [Details](#user-content-99722b982425634698e6339385ec4b75-81c33195)
[support/azure/app-service/troubleshoot-vnet-integration-apps.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/troubleshoot-vnet-integration-apps.md) | :warning:Warning | | [Details](#user-content-0a4c7560f1d62df072122d865a89cc05-81c33195)

<a id="99722b982425634698e6339385ec4b75-81c33195"></a>
### [support/azure/articles/appservice/quickstart-custom-container.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/articles/appservice/quickstart-custom-container.md)
 - **Line 15, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-visual-studio-pivot.md'.`````
 - **Line 19, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-linux-visual-studio-code-pivot.md'.`````
 - **Line 23, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-linux-azure-portal-pivot.md'.`````
 - **Line 27, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-azure-portal-pivot.md'.`````
 - **Line 31, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-powershell-pivot.md'.`````
 - **Line 35, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/quickstart-custom-container/quickstart-custom-container-windows-cli-pivot.md'.`````
 - **Line 2, Column 1**: **[Warning: ms-prod-or-service-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="0a4c7560f1d62df072122d865a89cc05-81c33195"></a>
### [support/azure/app-service/troubleshoot-vnet-integration-apps.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/troubleshoot-vnet-integration-apps.md)
 - **Line 50, Column 148**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../articles/app-service/quickstart-custom-container.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210142242109751-751/BuildReport?accessString=60d02907f72f226c20ee10cd7f13d28489cecb8cbc3e7e835c1aa3e30ac9cbe9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[a692415](https://github.com/hepiet/SupportArticles-docs/commits/a692415d4f28e028110195db9075a64f692c35ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter01.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter01.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter02.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter02.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter03.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter03.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter04.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter04.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter05.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter05.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/privateipkudu.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/privateipkudu.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/privateiplinux.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/privateiplinux.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/privateipwindows.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/privateipwindows.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/troubleshoot-vnet-integration-apps.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/troubleshoot-vnet-integration-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210142257589867-751/BuildReport?accessString=19eb620f423bbbd8ea8dc43ddbeb261e57c31417140e4234d219e2b105957d5b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by AmandaAZ** [comment]
@hepiet Thanks for your contribution. We will send the new topic to the triage team for review. You can check the work item AB#168238 for the latest status.

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[a692415](https://github.com/hepiet/SupportArticles-docs/commits/a692415d4f28e028110195db9075a64f692c35ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter01.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter01.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter02.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter02.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter03.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter03.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter04.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter04.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter05.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/networktroubleshooter05.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/privateipkudu.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/privateipkudu.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/privateiplinux.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/privateiplinux.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/media/vnet-integration-tsg/privateipwindows.png](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/media/vnet-integration-tsg/privateipwindows.png) | :white_check_mark:Succeeded | |
[support/azure/app-service/troubleshoot-vnet-integration-apps.md](https://github.com/hepiet/SupportArticles-docs/blob/hepiet-tsg1/support/azure/app-service/troubleshoot-vnet-integration-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202210180734196465-751/BuildReport?accessString=898cb1388e1ac7b431fa32b089383f4616bdc7f7a50821f85d745068f7db98a8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by genlin** [comment]
Close this PR and move the content to https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/3456

**Pull request closed without merging**
