### PR TITLE
Added a new doc for cloud-init

### PR DESCRIPTION
**Pull request by srijang**
Add a new doc -- url: /azure/virtual-machines/Cloud-init-deployment-delay

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@srijang : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by srijang** [comment]
#sign-off

**Comment by PRMerger3** [comment]
@srijang: I'm sorry - only the author of this article, @genlin  #Required; your GitHub user alias, with correct capitalization., can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by AmandaAZ** [comment]
@srijang  The Cloud-init-deployment-delay.md file can't be found in https://github.com/MicrosoftDocs/azure-docs/tree/master/articles/virtual-machines. Could you check whether you commit this file? Thanks.

**Comment by PRMerger20** [comment]
Microsoft authors of articles need to make updates through the private repository, so the updates can be staged and validated by current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged. 

It's easy to access the private repo version of your articles in GitHub. Just add *-pr* to the URL, as follows: 

 &nbsp;Public repo URL: `https://github.com/MicrosoftDocs/{docs-repo}` 
 &nbsp;Private repo URL: `https://github.com/MicrosoftDocs/{docs-repo-pr}` 

 We have closed this pull request. Please resubmit the updates through the private repo. For more information, see the [contributor guide](https://docs.microsoft.com/contribute/).

**Comment by mimckitt** [comment]
#reopen

**Pull request closed without merging**
