### PR TITLE
Update allocation-failure.md

### PR DESCRIPTION
**Pull request by travismaier**
Updated guidance on restart vs. start and removed redeployment as workaround

### CODE REVIEW

**Comment by PRMerger12** [comment]
@travismaier : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@travismaier : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
