### PR TITLE
Adding documentation to help where the Active Directory validation fa…

### PR DESCRIPTION
**Pull request by fuixx217**
…ils during a Failover Cluster Validation test against the System Configuration item.  The error was being troubleshot under case 2311020030005109

# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Comment by fuixx217** [comment]
This is a somewhat unique scenario, but it might help others who come across the errors mentioned.  I had a new Windows Server Failover cluster built in a new VM private cloud environment, and that new private cloud was put on a new domain (contoso2 in the example document).  My AD user performing the work resides on the old domain (contoso in the example document).

I was attempting to take a computer from the old domain, attach to the new domain, and then add that computer as a node in the cluster on the new domain.  At the time of troubleshooting this, there was a computer object in both contoso and contoso2 with the same name.  The System Configuration check of the Cluster Validation Wizard must search the domain of the user running the command for a computer object of the nodes, or the node attempting to be added, and when it finds it, the result was a Kerberos error that I found while running network tracing.

**Comment by fuixx217** [comment]
I wasn't sure what to put in for author values.  Please update appropriately.

**Comment by v-lianna** [comment]
@fuixx217 Thanks for adding the article to the troubleshoot repo. Please let me know if the PR is ready for review. Next time, you can directly create PRs to add new articles or update existing content in the [private repo](https://github.com/MicrosoftDocs/SupportArticles-docs-pr).

**Comment by fuixx217** [comment]
Good to know about the private repo.  I would say this is ready for review,
once the author information is updated.

**Comment by v-lianna** [comment]
@fuixx217 Thanks for bringing this to our attention. We have forwarded the information to engineering to investigate further. However, we will not be publishing this information at this time.

**Pull request closed without merging**
