### PR TITLE
Added PowerShell usage example, fixed path

### PR DESCRIPTION
**Pull request by zbalkan**
The event log path is fixed. Also added a sample PowerShell commands for ease of use.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@zbalkan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@zbalkan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Deland-Han — COMMENTED** [review]
some edits.

**Comment by PRMerger12** [comment]
@Deland-Han : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
