### PR TITLE
Change `HTT` to `HTTP` / Update versions applied to issue

### PR DESCRIPTION
**Pull request by blakedrumm**

### CODE REVIEW

**Comment by PRMerger3** [comment]
@blakedrumm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger-2** [comment]
@simonxjx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by simonxjx** [comment]
@blakedrumm Could you let us know if the PR is ready for review or merge?

**Comment by x-limitless-x** [comment]
#sign-off

**Comment by blakedrumm** [comment]
#sign-off

**Pull request merged**
