### PR TITLE
Update linux-recovery-cannot-start-file-system-errors.md

### PR DESCRIPTION
**Pull request by pagienge**
Complete rewrite, existing document lacked clarity and consistency in examples.  Doc is linked in Azure guided troubleshooters

### CODE REVIEW

**Comment by PRMerger17** [comment]
@pagienge : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AmandaAZ** [comment]
@pagienge Thanks for your contribution. We will work on this article. Let me know if this article is urgent.

**Comment by PRMerger19** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AmandaAZ** [comment]
@pagienge I made editorial changes to your content. Could you review them? Let me know if there is any comment. In addition, I don't have a lab environment to test the commands and outputs introduced in the article. Ensure they are correct when you review the article. Thanks.

**Comment by PRMerger4** [comment]
@pagienge : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AmandaAZ** [comment]
@pagienge Thanks for your review and improving my changes. I'm moving this PR to our edit process for matching global English standards. Let me know if you have other comments.

**Comment by PRMerger15** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[9d5b144](https://github.com/pagienge/SupportArticles-docs/commits/9d5b144bb5808a84004221c434c3c690e667374f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/virtual-machines/unlock-encrypted-linux-disk-offline-repair.md](https://github.com/pagienge/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/unlock-encrypted-linux-disk-offline-repair.md) | :warning:Warning | | [Details](#user-content-b43ed9d45b5d84c905320802d24ac70c-b5cc7f1c)
[support/azure/virtual-machines/linux-recovery-cannot-start-file-system-errors.md](https://github.com/pagienge/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/linux-recovery-cannot-start-file-system-errors.md) | :white_check_mark:Succeeded | |

<a id="b43ed9d45b5d84c905320802d24ac70c-b5cc7f1c"></a>
### [support/azure/virtual-machines/unlock-encrypted-linux-disk-offline-repair.md](https://github.com/pagienge/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/unlock-encrypted-linux-disk-offline-repair.md)
 - **Line 324, Column 176**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#repair-the-vm-offline' in 'azure/virtual-machines/linux-recovery-cannot-start-file-system-errors.md'.`````
 - **Line 407, Column 157**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#repair-the-vm-offline' in 'azure/virtual-machines/linux-recovery-cannot-start-file-system-errors.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202208010530080986-653/BuildReport?accessString=d662910a65ee0249def75ff5aa5817f857d867ae583e8bfe0cee60565710f313).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by PRMerger12** [comment]
@AmandaAZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[9e3c2c9](https://github.com/pagienge/SupportArticles-docs/commits/9e3c2c97a70c2b8df3bd2edad2b268adb20d7169)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/virtual-machines/linux-recovery-cannot-start-file-system-errors.md](https://github.com/pagienge/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/linux-recovery-cannot-start-file-system-errors.md) | :white_check_mark:Succeeded | |
[support/azure/virtual-machines/unlock-encrypted-linux-disk-offline-repair.md](https://github.com/pagienge/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/unlock-encrypted-linux-disk-offline-repair.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202208050857591620-653/BuildReport?accessString=0d733152045c8adf48ac71acae57b2355112b53f416c460b6a55c06506c6f318).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Docs Build status updates of commit _[9e3c2c9](https://github.com/pagienge/SupportArticles-docs/commits/9e3c2c97a70c2b8df3bd2edad2b268adb20d7169)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/azure/virtual-machines/linux-recovery-cannot-start-file-system-errors.md](https://github.com/pagienge/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/linux-recovery-cannot-start-file-system-errors.md) | :white_check_mark:Succeeded | |
[support/azure/virtual-machines/unlock-encrypted-linux-disk-offline-repair.md](https://github.com/pagienge/SupportArticles-docs/blob/patch-3/support/azure/virtual-machines/unlock-encrypted-linux-disk-offline-repair.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202208080612049909-653/BuildReport?accessString=6e6d529a201a31065fd9f45bfbf803c482cdb3ab7dd61dba51e6b2c16ed72356).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
