### PR TITLE
Update microsoft-dynamics-gp-stops-responding-crashes.md

### PR DESCRIPTION
**Pull request by theley502**

### CODE REVIEW

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[d153eb4](https://github.com/theley502/SupportArticles-docs/commits/d153eb4013aa6807bc378f4fdbd5ec9d88b7d927)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/dynamics/gp/microsoft-dynamics-gp-stops-responding-crashes.md](https://github.com/theley502/SupportArticles-docs/blob/patch-4/support/dynamics/gp/microsoft-dynamics-gp-stops-responding-crashes.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202211300206418952-798/BuildReport?accessString=cb71c45f75e133b646c74291d59e9c06b90ab5c30edf37ccf4b26556e5e09559).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[d153eb4](https://github.com/theley502/SupportArticles-docs/commits/d153eb4013aa6807bc378f4fdbd5ec9d88b7d927)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/dynamics/gp/microsoft-dynamics-gp-stops-responding-crashes.md](https://github.com/theley502/SupportArticles-docs/blob/patch-4/support/dynamics/gp/microsoft-dynamics-gp-stops-responding-crashes.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202211301018157535-798/BuildReport?accessString=1a4c4a430e3051569f5f8f92e5eaf4ee7c8546044de8a6602b0cd927ec4e6959).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by kaushika-msft** [comment]
Learn Build status updates of commit _[480bca7](https://github.com/theley502/SupportArticles-docs/commits/480bca767d9685d3e04ad7529d6b3fc2d786a38a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[support/dynamics/gp/microsoft-dynamics-gp-stops-responding-crashes.md](https://github.com/theley502/SupportArticles-docs/blob/patch-4/support/dynamics/gp/microsoft-dynamics-gp-stops-responding-crashes.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/07c79912-15d2-f5bd-767a-66d227fce918/202212020516295155-798/BuildReport?accessString=87775d11dd3506f568c15e887e8c46a40381fc9e86fd81898897714eac75cc62).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/07c79912-15d2-f5bd-767a-66d227fce918?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by lucciz01** [comment]
@theley502, Hi Terry, I have committed minor changes to the article. Feel free to let me know if any questions. Thanks!

**Review by ChristySu — APPROVED** [review]
Approved

**Pull request merged**
