### PR TITLE
[21 migrated D365 Guides and Remote Assist articles] Add guides and ra

### PR DESCRIPTION
**Pull request by v-wendysmith**
# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

### CODE REVIEW

**Comment by m-hartmann** [comment]
@v-wendysmith for the invalid link issues, please update the link path to **/**dynamics365/mixed-reality/*

For the missing ms.service value, update the docfx.json file in the support root folder. On line 288, add two new lines with the following code
`
        "dynamics-365/guides/**/**.*": "dynamics-365-guides",
        "dynamics-365/remote-assist/**/**.*": "dynamics-365-remote-assist",
`

That should take care of the errors on that build.

**Comment by m-hartmann** [comment]
When I first entered my comment, it also had some weird asterisk characters. This is the correct syntax: [Update your client app](/dynamics365/mixed-reality/guides/upgrade).

________________________________

**Comment by v-wendysmith** [comment]
Ok that makes sense. 🙂

Thanks
________________________________

**Comment by m-hartmann** [comment]
#sign-off

**Comment by m-hartmann** [comment]
#sign-off

**Comment by v-wendysmith** [comment]
#sign-off

**Pull request merged**
