### PR TITLE
v-chgri-commerce-ts-mig_2

### PR DESCRIPTION
**Pull request by v-chgri**
# Pull request guidance

Thank you for your contribution. The content team is monitoring the pull requests. Once your pull request is ready for review, please type "#sign-off" in a new comment or add a comment such as "PR is ready for review and merge."

### CODE REVIEW

**Comment by v-chgri** [comment]
This PR for Dynamics 365 Commerce troubleshooting article migration is a work in progress, please don't merge it until someone from Jo Sawyer's team signs off here. Thank you!

**Comment by lucciz01** [comment]
Hi @v-chgri, Thank you for your contribution. Once your pull request is ready for review, you can type "#sign-off" in a new comment or add a comment such as "PR is ready for review and merge." Then, we'll start to review the articles for you.

**Comment by lucciz01** [comment]
> This PR for Dynamics 365 Commerce troubleshooting article migration is a work in progress, please don't merge it until someone from Jo Sawyer's team signs off here. Thank you!

Hi @v-chgri, thanks for this notice!

**Comment by v-chgri** [comment]
#sign-off 

This PR is ready for review and merge. Article content is what is currently on the Commerce site. I've edited the toc.yml and welcome-commerce.yml files to reference the articles, but am unable to preview pages at this time. Please review the work done and let josaw and cgriffin@aquent.com know of any issues/comments/concerns. Thanks!

**Comment by josaw1** [comment]
#sign-off
This PR is ready for review and merge. Article content is what is currently on the Commerce site. I've edited the toc.yml and welcome-commerce.yml files to reference the articles, but am unable to preview pages at this time. (from Chris) Please review the work done and let josaw and cgriffin@aquent.com know of any issues/comments/concerns. Thanks!

**Comment by lucciz01** [comment]
Thanks @v-chgri and @josaw1. We'll get started on this work and will let you know once this PR is ready for your final review.

**Comment by lucciz01** [comment]
Close this PR because the articles are reviewed and published via private repo.

**Comment by venusmi** [comment]
[https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/4895](url)

**Pull request closed without merging**
